# This is a basic workflow to help you get started with Actions

name: Dev CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [dev/*, release/*, feature/*]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Installs rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Runs cargo test
      - uses: actions-rs/cargo@v1
        with:
          command: test

      - run: echo Building WASM package

      - name: wasm-pack-action download
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install (eg. "v0.9.1", "latest")
          version: latest # optional, default is latest
      - run: wasm-pack build
